// Generated by gencpp from file seed_r7_ros_controller/LedControl.msg
// DO NOT EDIT!


#ifndef SEED_R7_ROS_CONTROLLER_MESSAGE_LEDCONTROL_H
#define SEED_R7_ROS_CONTROLLER_MESSAGE_LEDCONTROL_H

#include <ros/service_traits.h>


#include <seed_r7_ros_controller/LedControlRequest.h>
#include <seed_r7_ros_controller/LedControlResponse.h>


namespace seed_r7_ros_controller
{

struct LedControl
{

typedef LedControlRequest Request;
typedef LedControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LedControl
} // namespace seed_r7_ros_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::seed_r7_ros_controller::LedControl > {
  static const char* value()
  {
    return "f29b351f80354f5bbb09b425fecd0cc2";
  }

  static const char* value(const ::seed_r7_ros_controller::LedControl&) { return value(); }
};

template<>
struct DataType< ::seed_r7_ros_controller::LedControl > {
  static const char* value()
  {
    return "seed_r7_ros_controller/LedControl";
  }

  static const char* value(const ::seed_r7_ros_controller::LedControl&) { return value(); }
};


// service_traits::MD5Sum< ::seed_r7_ros_controller::LedControlRequest> should match
// service_traits::MD5Sum< ::seed_r7_ros_controller::LedControl >
template<>
struct MD5Sum< ::seed_r7_ros_controller::LedControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::seed_r7_ros_controller::LedControl >::value();
  }
  static const char* value(const ::seed_r7_ros_controller::LedControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_r7_ros_controller::LedControlRequest> should match
// service_traits::DataType< ::seed_r7_ros_controller::LedControl >
template<>
struct DataType< ::seed_r7_ros_controller::LedControlRequest>
{
  static const char* value()
  {
    return DataType< ::seed_r7_ros_controller::LedControl >::value();
  }
  static const char* value(const ::seed_r7_ros_controller::LedControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::seed_r7_ros_controller::LedControlResponse> should match
// service_traits::MD5Sum< ::seed_r7_ros_controller::LedControl >
template<>
struct MD5Sum< ::seed_r7_ros_controller::LedControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::seed_r7_ros_controller::LedControl >::value();
  }
  static const char* value(const ::seed_r7_ros_controller::LedControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_r7_ros_controller::LedControlResponse> should match
// service_traits::DataType< ::seed_r7_ros_controller::LedControl >
template<>
struct DataType< ::seed_r7_ros_controller::LedControlResponse>
{
  static const char* value()
  {
    return DataType< ::seed_r7_ros_controller::LedControl >::value();
  }
  static const char* value(const ::seed_r7_ros_controller::LedControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEED_R7_ROS_CONTROLLER_MESSAGE_LEDCONTROL_H
