// Generated by gencpp from file seed_r7_ros_controller/ResetRobotStatus.msg
// DO NOT EDIT!


#ifndef SEED_R7_ROS_CONTROLLER_MESSAGE_RESETROBOTSTATUS_H
#define SEED_R7_ROS_CONTROLLER_MESSAGE_RESETROBOTSTATUS_H

#include <ros/service_traits.h>


#include <seed_r7_ros_controller/ResetRobotStatusRequest.h>
#include <seed_r7_ros_controller/ResetRobotStatusResponse.h>


namespace seed_r7_ros_controller
{

struct ResetRobotStatus
{

typedef ResetRobotStatusRequest Request;
typedef ResetRobotStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetRobotStatus
} // namespace seed_r7_ros_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::seed_r7_ros_controller::ResetRobotStatus > {
  static const char* value()
  {
    return "6cdbff96eb47c9283a67a20f729609c5";
  }

  static const char* value(const ::seed_r7_ros_controller::ResetRobotStatus&) { return value(); }
};

template<>
struct DataType< ::seed_r7_ros_controller::ResetRobotStatus > {
  static const char* value()
  {
    return "seed_r7_ros_controller/ResetRobotStatus";
  }

  static const char* value(const ::seed_r7_ros_controller::ResetRobotStatus&) { return value(); }
};


// service_traits::MD5Sum< ::seed_r7_ros_controller::ResetRobotStatusRequest> should match
// service_traits::MD5Sum< ::seed_r7_ros_controller::ResetRobotStatus >
template<>
struct MD5Sum< ::seed_r7_ros_controller::ResetRobotStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::seed_r7_ros_controller::ResetRobotStatus >::value();
  }
  static const char* value(const ::seed_r7_ros_controller::ResetRobotStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_r7_ros_controller::ResetRobotStatusRequest> should match
// service_traits::DataType< ::seed_r7_ros_controller::ResetRobotStatus >
template<>
struct DataType< ::seed_r7_ros_controller::ResetRobotStatusRequest>
{
  static const char* value()
  {
    return DataType< ::seed_r7_ros_controller::ResetRobotStatus >::value();
  }
  static const char* value(const ::seed_r7_ros_controller::ResetRobotStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::seed_r7_ros_controller::ResetRobotStatusResponse> should match
// service_traits::MD5Sum< ::seed_r7_ros_controller::ResetRobotStatus >
template<>
struct MD5Sum< ::seed_r7_ros_controller::ResetRobotStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::seed_r7_ros_controller::ResetRobotStatus >::value();
  }
  static const char* value(const ::seed_r7_ros_controller::ResetRobotStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_r7_ros_controller::ResetRobotStatusResponse> should match
// service_traits::DataType< ::seed_r7_ros_controller::ResetRobotStatus >
template<>
struct DataType< ::seed_r7_ros_controller::ResetRobotStatusResponse>
{
  static const char* value()
  {
    return DataType< ::seed_r7_ros_controller::ResetRobotStatus >::value();
  }
  static const char* value(const ::seed_r7_ros_controller::ResetRobotStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEED_R7_ROS_CONTROLLER_MESSAGE_RESETROBOTSTATUS_H
