// Generated by gencpp from file seed_r7_ros_controller/ResetRobotStatusRequest.msg
// DO NOT EDIT!


#ifndef SEED_R7_ROS_CONTROLLER_MESSAGE_RESETROBOTSTATUSREQUEST_H
#define SEED_R7_ROS_CONTROLLER_MESSAGE_RESETROBOTSTATUSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace seed_r7_ros_controller
{
template <class ContainerAllocator>
struct ResetRobotStatusRequest_
{
  typedef ResetRobotStatusRequest_<ContainerAllocator> Type;

  ResetRobotStatusRequest_()
    : reset(false)  {
    }
  ResetRobotStatusRequest_(const ContainerAllocator& _alloc)
    : reset(false)  {
  (void)_alloc;
    }



   typedef uint8_t _reset_type;
  _reset_type reset;





  typedef boost::shared_ptr< ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetRobotStatusRequest_

typedef ::seed_r7_ros_controller::ResetRobotStatusRequest_<std::allocator<void> > ResetRobotStatusRequest;

typedef boost::shared_ptr< ::seed_r7_ros_controller::ResetRobotStatusRequest > ResetRobotStatusRequestPtr;
typedef boost::shared_ptr< ::seed_r7_ros_controller::ResetRobotStatusRequest const> ResetRobotStatusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator1> & lhs, const ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator2> & rhs)
{
  return lhs.reset == rhs.reset;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator1> & lhs, const ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace seed_r7_ros_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba4b0b221fb425ac5eaf73f71ae34971";
  }

  static const char* value(const ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba4b0b221fb425acULL;
  static const uint64_t static_value2 = 0x5eaf73f71ae34971ULL;
};

template<class ContainerAllocator>
struct DataType< ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seed_r7_ros_controller/ResetRobotStatusRequest";
  }

  static const char* value(const ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool reset\n"
;
  }

  static const char* value(const ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetRobotStatusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seed_r7_ros_controller::ResetRobotStatusRequest_<ContainerAllocator>& v)
  {
    s << indent << "reset: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEED_R7_ROS_CONTROLLER_MESSAGE_RESETROBOTSTATUSREQUEST_H
