// Generated by gencpp from file seed_r7_ros_controller/SetInitialPose.msg
// DO NOT EDIT!


#ifndef SEED_R7_ROS_CONTROLLER_MESSAGE_SETINITIALPOSE_H
#define SEED_R7_ROS_CONTROLLER_MESSAGE_SETINITIALPOSE_H

#include <ros/service_traits.h>


#include <seed_r7_ros_controller/SetInitialPoseRequest.h>
#include <seed_r7_ros_controller/SetInitialPoseResponse.h>


namespace seed_r7_ros_controller
{

struct SetInitialPose
{

typedef SetInitialPoseRequest Request;
typedef SetInitialPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInitialPose
} // namespace seed_r7_ros_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::seed_r7_ros_controller::SetInitialPose > {
  static const char* value()
  {
    return "afcf37822d0374e399bbea551fc3f563";
  }

  static const char* value(const ::seed_r7_ros_controller::SetInitialPose&) { return value(); }
};

template<>
struct DataType< ::seed_r7_ros_controller::SetInitialPose > {
  static const char* value()
  {
    return "seed_r7_ros_controller/SetInitialPose";
  }

  static const char* value(const ::seed_r7_ros_controller::SetInitialPose&) { return value(); }
};


// service_traits::MD5Sum< ::seed_r7_ros_controller::SetInitialPoseRequest> should match
// service_traits::MD5Sum< ::seed_r7_ros_controller::SetInitialPose >
template<>
struct MD5Sum< ::seed_r7_ros_controller::SetInitialPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::seed_r7_ros_controller::SetInitialPose >::value();
  }
  static const char* value(const ::seed_r7_ros_controller::SetInitialPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_r7_ros_controller::SetInitialPoseRequest> should match
// service_traits::DataType< ::seed_r7_ros_controller::SetInitialPose >
template<>
struct DataType< ::seed_r7_ros_controller::SetInitialPoseRequest>
{
  static const char* value()
  {
    return DataType< ::seed_r7_ros_controller::SetInitialPose >::value();
  }
  static const char* value(const ::seed_r7_ros_controller::SetInitialPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::seed_r7_ros_controller::SetInitialPoseResponse> should match
// service_traits::MD5Sum< ::seed_r7_ros_controller::SetInitialPose >
template<>
struct MD5Sum< ::seed_r7_ros_controller::SetInitialPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::seed_r7_ros_controller::SetInitialPose >::value();
  }
  static const char* value(const ::seed_r7_ros_controller::SetInitialPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_r7_ros_controller::SetInitialPoseResponse> should match
// service_traits::DataType< ::seed_r7_ros_controller::SetInitialPose >
template<>
struct DataType< ::seed_r7_ros_controller::SetInitialPoseResponse>
{
  static const char* value()
  {
    return DataType< ::seed_r7_ros_controller::SetInitialPose >::value();
  }
  static const char* value(const ::seed_r7_ros_controller::SetInitialPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEED_R7_ROS_CONTROLLER_MESSAGE_SETINITIALPOSE_H
